version: "3.7"

services:
  nginx:
    restart: always
    build:
      context: ./nginx
    depends_on:
      - client
    ports:
      - "3080:80"
  client:
    stdin_open: true
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app